version: "3.8"

services:
  backend:
    build: ./mui-backend
    image: prabodhaj/muiapp-backend
    container_name: backend_container
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACKEND_PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    build: ./mui-frontend
    image: prabodhaj/muiapp-frontend
    container_name: frontend_container
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
